name = "ballerz-api"
main = "src/index.ts"
compatibility_date = "2026-10-01"
workers_dev = false
routes = [{ pattern = "ballerz.cloud/baller/*", zone_name = "ballerz.cloud" }]

[[kv_namespaces]]
binding = "BALLER"
id = "ec2bd233d0b14daaa6fa8b9b9df285b0"
preview_id = "84a56abe24d84240847cb57cd4e3a2fa"

[observability]
enabled = true
